import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextAuthSessionProvider from "@/components/providers/session-provider"
import { ThemeProvider } from "@/components/providers/theme-provider"
import { auth } from "@/lib/auth/auth"
import { Sidebar } from "@/components/layout/sidebar/sidebar"
import { Header } from "@/components/layout/header" // Import Header

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'EduTrack Pro',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth();
  const role = session?.user.role || "GUEST";

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
      </head>
      <body className={`h-screen ${inter.className}`}>
        {/* Skip to main content link for accessibility */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 bg-primary text-primary-foreground px-4 py-2 rounded-md z-50 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
          tabIndex={0}
        >
          Skip to main content
        </a>

        <NextAuthSessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex h-screen">
              <aside
                className="w-48 sm:w-56 lg:w-64 border-r bg-background flex-shrink-0 overflow-y-auto"
                role="navigation"
                aria-label="Main navigation"
              >
                <Sidebar role={role} session={session} />
              </aside>
              <div className="flex flex-col flex-1 min-w-0">
                <Header session={session} role={role} />
                <main
                  id="main-content"
                  className="flex-1 overflow-y-auto overflow-x-hidden focus:outline-none"
                  tabIndex={-1}
                  role="main"
                >
                  <div className="h-full">
                    {children}
                  </div>
                </main>
              </div>
            </div>
          </ThemeProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  )
}
