name: Smoke test (registration + login)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Full URL of deployed site (e.g. https://your-app.example). If empty, uses DEPLOY_URL secret.'
        required: false

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine target URL
        id: target
        run: |
          if [ -n "${{ github.event.inputs.target_url }}" ]; then
            echo "TARGET=${{ github.event.inputs.target_url }}" >> $GITHUB_OUTPUT
          elif [ -n "${{ secrets.DEPLOY_URL }}" ]; then
            echo "TARGET=${{ secrets.DEPLOY_URL }}" >> $GITHUB_OUTPUT
          else
            echo "No target_url input provided and DEPLOY_URL secret is not set. Failing." >&2
            exit 1
          fi

      - name: Wait for site to be reachable
        run: |
          TARGET=${{ steps.target.outputs.TARGET }}
          echo "Waiting for $TARGET to respond..."
          tries=0
          until curl -sf "$TARGET" >/dev/null; do
            tries=$((tries+1))
            if [ $tries -ge 30 ]; then
              echo "Timed out waiting for $TARGET" >&2
              exit 1
            fi
            sleep 5
          done
          echo "$TARGET is reachable"

      - name: Run registration smoke test
        env:
          TARGET: ${{ steps.target.outputs.TARGET }}
        run: |
          TIMESTAMP=$(date +%s)
          EMAIL="smoketest+${TIMESTAMP}@example.com"
          PAYLOAD=$(jq -n --arg n "Smoke Test" --arg e "$EMAIL" --arg p "Sm0keT3st!" '{name: $n, email: $e, password: $p}')
          echo "Registering user: $EMAIL"
          HTTP_CODE=$(curl -s -o /tmp/resp.json -w "%{http_code}" -X POST "$TARGET/api/auth/register" -H "Content-Type: application/json" -d "$PAYLOAD")
          echo "Response HTTP code: $HTTP_CODE"
          cat /tmp/resp.json || true
          if [[ "$HTTP_CODE" == "201" ]] || [[ "$HTTP_CODE" == "200" ]] || [[ "$HTTP_CODE" == "409" ]]; then
            echo "Registration endpoint returned acceptable HTTP code: $HTTP_CODE"
          else
            echo "Unexpected HTTP code from register: $HTTP_CODE" >&2
            exit 1
          fi

      - name: Check login page
        env:
          TARGET: ${{ steps.target.outputs.TARGET }}
        run: |
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$TARGET/auth/login")
          echo "Login page HTTP code: $HTTP_CODE"
          if [ "$HTTP_CODE" != "200" ]; then
            echo "Login page did not return 200" >&2
            exit 1
          fi

      - name: Sign in with credentials (NextAuth)
        env:
          TARGET: ${{ steps.target.outputs.TARGET }}
        run: |
          # Use the same test user created earlier
          TIMESTAMP=$(date +%s)
          EMAIL="smoketest+${TIMESTAMP}@example.com"
          PASSWORD="Sm0keT3st!"

          # Note: The registration step used a timestamped email; reuse the same timestamp if available.
          # For simplicity in the workflow, perform sign-up again and then sign-in.
          PAYLOAD=$(jq -n --arg n "Smoke Test" --arg e "$EMAIL" --arg p "$PASSWORD" '{name: $n, email: $e, password: $p}')
          curl -s -X POST "$TARGET/api/auth/register" -H "Content-Type: application/json" -d "$PAYLOAD" -o /tmp/register.json || true

          # Now sign in using NextAuth credentials callback
          SIGNIN_PAYLOAD=$(jq -n --arg e "$EMAIL" --arg p "$PASSWORD" '{csrfToken: null, callbackUrl: "/dashboard", json: true, username: $e, email: $e, password: $p}')

          # Perform sign-in and save cookies
          COOKIE_JAR=/tmp/cookies.txt
          rm -f $COOKIE_JAR || true
          HTTP_CODE=$(curl -s -w "%{http_code}" -c $COOKIE_JAR -X POST "$TARGET/api/auth/callback/credentials" -H "Content-Type: application/x-www-form-urlencoded" --data-urlencode "email=$EMAIL" --data-urlencode "password=$PASSWORD" -o /tmp/signin.html)
          echo "Sign-in HTTP code: $HTTP_CODE"
          if [[ "$HTTP_CODE" != "302" && "$HTTP_CODE" != "200" ]]; then
            echo "Sign-in did not redirect or return success (code $HTTP_CODE)" >&2
            cat /tmp/signin.html || true
            exit 1
          fi

          # Validate session using the cookies
          SESSION_JSON=$(curl -s -b $COOKIE_JAR "$TARGET/api/auth/session")
          echo "Session response: $SESSION_JSON"
          if echo "$SESSION_JSON" | grep -q "user"; then
            echo "Session contains user — sign-in verified"
          else
            echo "Session did not contain user info" >&2
            exit 1
          fi

      - name: Success message
        run: echo "Smoke test passed against ${{ steps.target.outputs.TARGET }}"
